Alert
ranitasahaa1230/Kolpotoru-UI-Component-Library pull request #1
Opened 2022-01-29 15:59 UTC by ranitasahaa1230

Please review my alert component!

2022-01-29 16:07 UTC, Rohitprasad83 requested changes

2022-01-29 16:07 UTC, Rohitprasad83 commented on Alert/alert.css
> +.success-alert,.warning-alert, .error-alert, .info-alert, .outline-success, .outline-warning, .outline-info, .outline-error, .filled-success,.filled-warning, .filled-error, .filled-info{
rather than applying the same properties to different classes, create a single class and add this to HTML element. this CSS file looks better.

2022-01-29 16:14 UTC, maitrakhatri requested changes
all the alerts have border 2px solid common, so instead of repeating it in all of them create a new class and give the CSS.

Also, you have used all the hex code, instead define the colors in :root and use variable names for easy use.

2022-01-29 16:44 UTC, saicharan-gouru approved these changes
Looks good.

2022-01-29 16:47 UTC, Rohitprasad83 approved these changes
Looks perfect!

2022-01-30 14:08 UTC, maitrakhatri approved these changes

2022-01-31 15:46 UTC, merged